# -*- coding: utf-8 -*-
"""IA-1_LVADSUSR175.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbaHd1NmWTQTS0IewZqOTBhyuvDlQRmd
"""

#LAB Section 1

# 1.
length = int(input("Enter length of your property : "))
width = int(input("Enter width of your property : "))
area = length*width
if area <=500:
  print(area," Small property")
elif (501<area <=1000):
  print(area,"Medium Property")
else:
  print(area,"large Property")

# 2.
import math
import os
weight = int(input("Enter your weight in kg :"))
height = int(input("Enter your height in m :"))
BMI = weight/pow(height,2)
print(BMI)

# 3
SD_RECORDS = {{"SID":101}:{{"MATH":88},{"English":77},{"Science":88}}}
SD_RECORDS[101]

# 4.
Age = int(input("Enter your age:"))
if Age <=12:
  print("Please watch Children Movies")
elif (12<Age<=20):
  print("Please watch teen age movies")
elif (21<=Age<=45):
  print("Please watch Adult based movies")
else:
  print("Please watch Senior Collections")

# 5.
list1 = [1,2,3,4,5,6,7,8,9,10,11,12]
list2 = []
for i in list1:
  if i%2 == 0:
    list2.append(i)
  else:
    continue
print(list2)

#6.
password = "praha"
while(True):
  user_input = input("Enter your password:")
  if(user_input == password):
    print("correct passowrd, welcome !")
    break
  else:
    print("OOops Incorrect passowrd, Try again !!! ")

#7.
import math
list1 = [1,2,3,4,5]
def avg(list1):
  sum =0
  for i in range(0,len(list1)):
    sum+= list1[i]
  average = sum/len(list1)
  print(average)
avg(list1)

#8.
string = input("Enter the feedback ")
def no_vowels(string):
  ans = 0
  for i in range(0,len(string)):
    if(string[i]=='a' or string[i] == 'e' or string[i] == 'i' or string[i] == 'o' or string[i] == 'u'):
      ans+=1
  print(ans)
no_vowels(string)

#9.
import datetime
current_time = datetime.datetime.now()
print(current_time)

# 10.
try:
    n1 = int(input("enter your 1st loan installment :"))
    n2 = int(input("enter your 2nd loan installment :"))
    sum = n1+n2
    print(sum)
except:
    print("Enter numeric values only")

# 11.
try:
  n = int(input())
  print(n)
except ValueError:
  print("Only integers pls")

#12.

try:
    n1 = int(input("Enter your number n1: "))
    n2 = int(input("Enter your number n2: "))
    div = n1/n2
    print(div)
except ZeroDivisionError:
    print("Denominator should not be Zero")

#13.
log = open('/sample_data/IA.csv','w')
log.write("Hello,Python")

#14.
log2 = open('/sample_data/IA.csv','r')
print(log2.read())
log2.close()

#15.

log2 = open('/sample_data/IA.csv','w')
li= []
lines = input()
li.append(lines)
log2.writelines(li)
log2.read()
log2.close()